services:
  redis:
    image: redis:7
    networks:
      - network_public
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --port 6379
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
networks:
  network_public:
    external: true
    name: network_public
volumes:
  redis-data:
    driver: local
